package io.starter.model;

public class Product {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.sku
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String sku;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.name
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.description
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.price
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Float price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.tax
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String tax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column product.type
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.id
	 * @return  the value of product.id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.id
	 * @param id  the value for product.id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.sku
	 * @return  the value of product.sku
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getSku() {
		return sku;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.sku
	 * @param sku  the value for product.sku
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setSku(String sku) {
		this.sku = sku;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.name
	 * @return  the value of product.name
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.name
	 * @param name  the value for product.name
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.description
	 * @return  the value of product.description
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.description
	 * @param description  the value for product.description
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.price
	 * @return  the value of product.price
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Float getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.price
	 * @param price  the value for product.price
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setPrice(Float price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.tax
	 * @return  the value of product.tax
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getTax() {
		return tax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.tax
	 * @param tax  the value for product.tax
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setTax(String tax) {
		this.tax = tax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column product.type
	 * @return  the value of product.type
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column product.type
	 * @param type  the value for product.type
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setType(Integer type) {
		this.type = type;
	}
}