package io.starter.model;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.Date;

import org.apache.ibatis.session.SqlSession;
import org.codehaus.jettison.json.JSONException;
import org.codehaus.jettison.json.JSONObject;
import org.json.JSONArray;

import com.extentech.ExtenXLS.WorkBookHandle;

public class Order {

	
	
	// relational object manual setup
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.date
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.event_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer eventId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.location_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer locationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.vehicle_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer vehicleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.customer_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.sales_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer salesId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.adjustment
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Float adjustment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.description
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order.purchase_order
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String purchaseOrder;


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.id
	 * @return  the value of order.id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.id
	 * @param id  the value for order.id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.date
	 * @return  the value of order.date
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.date
	 * @param date  the value for order.date
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.event_id
	 * @return  the value of order.event_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getEventId() {
		return eventId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.event_id
	 * @param eventId  the value for order.event_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setEventId(Integer eventId) {
		this.eventId = eventId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.location_id
	 * @return  the value of order.location_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getLocationId() {
		return locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.location_id
	 * @param locationId  the value for order.location_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.vehicle_id
	 * @return  the value of order.vehicle_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getVehicleId() {
		return vehicleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.vehicle_id
	 * @param vehicleId  the value for order.vehicle_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setVehicleId(Integer vehicleId) {
		this.vehicleId = vehicleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.customer_id
	 * @return  the value of order.customer_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.customer_id
	 * @param customerId  the value for order.customer_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.sales_id
	 * @return  the value of order.sales_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getSalesId() {
		return salesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.sales_id
	 * @param salesId  the value for order.sales_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setSalesId(Integer salesId) {
		this.salesId = salesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.adjustment
	 * @return  the value of order.adjustment
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Float getAdjustment() {
		return adjustment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.adjustment
	 * @param adjustment  the value for order.adjustment
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setAdjustment(Float adjustment) {
		this.adjustment = adjustment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.description
	 * @return  the value of order.description
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.description
	 * @param description  the value for order.description
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order.purchase_order
	 * @return  the value of order.purchase_order
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getPurchaseOrder() {
		return purchaseOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order.purchase_order
	 * @param purchaseOrder  the value for order.purchase_order
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setPurchaseOrder(String purchaseOrder) {
		this.purchaseOrder = purchaseOrder;
	}



	private User technician = null;
	
	
	public User getTechnician() {
		return technician;
	}

	public void setTechnician(User technician) {
		this.technician = technician;
	}



	private User customer = null;
	
	
	public User getCustomer() {
		return customer;
	}

	public void setCustomer(User customer) {
		this.customer = customer;
	}

	
	private CalendarEvent event = null;
	

	public CalendarEvent getEvent() {
		return event;
	}

	public void setEvent(CalendarEvent event) {
		this.event = event;
	}

	private Vehicle vehicle = null;
	
	public Vehicle getVehicle() {
		return vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}



	private Location location = null;
	

	public Location getLocation() {
		return location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	private List orderDetails = new ArrayList();

	public List getOrderDetails() {
		return orderDetails;
	}

	public void setOrderDetails(List orderDetails) {
		this.orderDetails = orderDetails;
	}
	
	private List payments = new ArrayList();

	public List getPayments() {
		return payments;
	}

	public void setPayments(List payments) {
		this.payments = payments;
	}

	
	/**
	 * return a human understandable version of this Order
	 */
	public String toString(){
		SimpleDateFormat sdf = new SimpleDateFormat("EEEE MMMM dd, yyyy h:MMa");
		String niceDate = sdf.format(this.getDate());
		return this.getDescription() + " on " + niceDate + " with " + this.getTechnician().getUsername();
	}
	
	/**
	 * create a nice order json array
	 * 
	 * @return
	 * @throws JSONException
	 */
	public JSONObject getJSON() throws JSONException{
		JSONObject job = new JSONObject("Order");
		job.put("description", this.getDescription());
		job.put("orderDetails", new JSONArray(this.getOrderDetails()));
		return job;
	}
	
	/**
	 * persist this object and all of its sub items
	 * @param session
	 * @return
	 */
	public boolean persist(SqlSession session){
		return false;
	}
	
	private WorkBookHandle orderInvoice = null;


	public WorkBookHandle getOrderInvoice() {
		return orderInvoice;
	}

	public void setOrderInvoice(WorkBookHandle orderInvoice) {
		this.orderInvoice = orderInvoice;
	}
}