package io.starter.model;

import java.util.Date;

public class OrderDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_detail.id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_detail.date
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Date date;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_detail.order_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_detail.product_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer productId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_detail.qty
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer qty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_detail.description
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_detail.price
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Float price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_detail.adjustment
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Float adjustment;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_detail.tax
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Float tax;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_detail.id
	 * @return  the value of order_detail.id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_detail.id
	 * @param id  the value for order_detail.id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_detail.date
	 * @return  the value of order_detail.date
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_detail.date
	 * @param date  the value for order_detail.date
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_detail.order_id
	 * @return  the value of order_detail.order_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_detail.order_id
	 * @param orderId  the value for order_detail.order_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_detail.product_id
	 * @return  the value of order_detail.product_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getProductId() {
		return productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_detail.product_id
	 * @param productId  the value for order_detail.product_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setProductId(Integer productId) {
		this.productId = productId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_detail.qty
	 * @return  the value of order_detail.qty
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getQty() {
		return qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_detail.qty
	 * @param qty  the value for order_detail.qty
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setQty(Integer qty) {
		this.qty = qty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_detail.description
	 * @return  the value of order_detail.description
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_detail.description
	 * @param description  the value for order_detail.description
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_detail.price
	 * @return  the value of order_detail.price
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Float getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_detail.price
	 * @param price  the value for order_detail.price
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setPrice(Float price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_detail.adjustment
	 * @return  the value of order_detail.adjustment
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Float getAdjustment() {
		return adjustment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_detail.adjustment
	 * @param adjustment  the value for order_detail.adjustment
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setAdjustment(Float adjustment) {
		this.adjustment = adjustment;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_detail.tax
	 * @return  the value of order_detail.tax
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Float getTax() {
		return tax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_detail.tax
	 * @param tax  the value for order_detail.tax
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setTax(Float tax) {
		this.tax = tax;
	}

	// relational manual setup
	private Product product = null;

	public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}
	
}