spring:
  application:
    name: stackgen-service-instance
  boot:
    admin:
      client:
        url: "http://localhost:8009"
        instance:
          service-base-url: "http://localhost:8009"
  profiles:
    active:
      - secure

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

---
spring:
  profiles: insecure

---
spring:
  profiles: secure
  security:
    user:
      name: "johnny"
      password: "shr3d1t"
  boot:
    admin:
      client:
        username: "johnny"       #These two are needed so that the client
        password: "shr3d1t"   #can register at the protected server api
        instance:
          metadata:
            user.name: "johnny"         #These two are needed so that the server
            user.password: "shr3d1t" #can access the protected client endpoints