swagger: '2.0'

        # TODO: type: string
        # format: uuid
        # example: d290f1ee-6c54-4b01-90e6-d701748f0851
info:
  description: This is the ml_opt_out microservice API
  version: 1.0.0
  title: The Company Mailing Opt-Out API
  # put the contact info for your development or API team
  contact:
    email: opt_out@company.com
  license:
    name: AGPL 3.0
    url: https://www.gnu.org/licenses/agpl-3.0.html
  termsOfService: http://company.com/tos/
servers:
  url: https://company.com:{port}/{basePath}
  description: The production API server
  variables:
    username:
      # note! no enum here means it is an open value
      default: demo
      description: this value is assigned by the service provider
    port:
      enum:
        - '8443'
        - '443'
      default: '8443'
    basePath:
      # open meaning there is the opportunity to use special base paths as assigned by the provider, default is `v2`
      default: v1
# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: users
  description: Operations available to regular users
schemes:
- https
paths:
  /user/login:
    post:
      tags:
      - "user"
      summary: "Logs user into the system"
      description: ""
      operationId: "loginUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "username"
        in: "query"
        description: "The user name for login"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"
        400:
          description: "Invalid username/password supplied"
  /user/logout:
    get:
      tags:
      - "user"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters: []
      responses:
        default:
          description: "successful operation"
securityDefinitions:
  automator_auth:
    type: "oauth2"
    authorizationUrl: "http://company.com/oauth/dialog"
    flow: "implicit"
    scopes:
      write:items: "modify items in your account"
      read:items: "read your items"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"                    
definitions:
  OptOuts:
    type: object
    required:
    - firstName
    - lastName
    - street1
    - city
    - state
    - zip
    properties:
      id:
        type: "integer"
        format: "int64"    
      firstName:
        type: string
        example: Wendy
        description: "full first name of individual"
      lastName:
        type: string
        example: Parker
        description: "full last name of individual"
      street1:
        type: string
        example: 123 Daydream Blvd.
        description: "Street address line 1"
      street2:
        type:  string
        example: Apt. 7
        description: "Street address line 2"
      city:
        type: string
        example: San Francisco       
        description: "full name of city"
      state:
        type:  string
        format: "date-time"
        description: "2 character state code (upper case)"
      zip:
        type: string
        example: 94210
        description: "5 digit zip code"
    xml:
      name: "OptOuts" 
externalDocs:
  description: "StackGen"
  url: "http://docs.stackgen.io/"