package io.starter.model;

public class LocationResourceIdx {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location_resource_idx.id
	 * @mbggenerated  Fri Feb 06 08:36:52 PST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location_resource_idx.location_id
	 * @mbggenerated  Fri Feb 06 08:36:52 PST 2015
	 */
	private Integer locationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location_resource_idx.resource_id
	 * @mbggenerated  Fri Feb 06 08:36:52 PST 2015
	 */
	private Integer resourceId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location_resource_idx.id
	 * @return  the value of location_resource_idx.id
	 * @mbggenerated  Fri Feb 06 08:36:52 PST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location_resource_idx.id
	 * @param id  the value for location_resource_idx.id
	 * @mbggenerated  Fri Feb 06 08:36:52 PST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location_resource_idx.location_id
	 * @return  the value of location_resource_idx.location_id
	 * @mbggenerated  Fri Feb 06 08:36:52 PST 2015
	 */
	public Integer getLocationId() {
		return locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location_resource_idx.location_id
	 * @param locationId  the value for location_resource_idx.location_id
	 * @mbggenerated  Fri Feb 06 08:36:52 PST 2015
	 */
	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location_resource_idx.resource_id
	 * @return  the value of location_resource_idx.resource_id
	 * @mbggenerated  Fri Feb 06 08:36:52 PST 2015
	 */
	public Integer getResourceId() {
		return resourceId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location_resource_idx.resource_id
	 * @param resourceId  the value for location_resource_idx.resource_id
	 * @mbggenerated  Fri Feb 06 08:36:52 PST 2015
	 */
	public void setResourceId(Integer resourceId) {
		this.resourceId = resourceId;
	}
}