package io.starter.model;

public class LookupPostalCode {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lookup_postal_code.postal_code
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer postalCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lookup_postal_code.city
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lookup_postal_code.state
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lookup_postal_code.latitude
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Float latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lookup_postal_code.longitude
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Float longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lookup_postal_code.timezone
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer timezone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column lookup_postal_code.flag
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer flag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lookup_postal_code.postal_code
	 * @return  the value of lookup_postal_code.postal_code
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getPostalCode() {
		return postalCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lookup_postal_code.postal_code
	 * @param postalCode  the value for lookup_postal_code.postal_code
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setPostalCode(Integer postalCode) {
		this.postalCode = postalCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lookup_postal_code.city
	 * @return  the value of lookup_postal_code.city
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lookup_postal_code.city
	 * @param city  the value for lookup_postal_code.city
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lookup_postal_code.state
	 * @return  the value of lookup_postal_code.state
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lookup_postal_code.state
	 * @param state  the value for lookup_postal_code.state
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lookup_postal_code.latitude
	 * @return  the value of lookup_postal_code.latitude
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Float getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lookup_postal_code.latitude
	 * @param latitude  the value for lookup_postal_code.latitude
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lookup_postal_code.longitude
	 * @return  the value of lookup_postal_code.longitude
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Float getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lookup_postal_code.longitude
	 * @param longitude  the value for lookup_postal_code.longitude
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lookup_postal_code.timezone
	 * @return  the value of lookup_postal_code.timezone
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getTimezone() {
		return timezone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lookup_postal_code.timezone
	 * @param timezone  the value for lookup_postal_code.timezone
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setTimezone(Integer timezone) {
		this.timezone = timezone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column lookup_postal_code.flag
	 * @return  the value of lookup_postal_code.flag
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column lookup_postal_code.flag
	 * @param flag  the value for lookup_postal_code.flag
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setFlag(Integer flag) {
		this.flag = flag;
	}
}