package io.starter.model;

public class Resource {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.name
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.user_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.calendar_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer calendarId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.location_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer locationId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.notes
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String notes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.status
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column resource.type
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.id
	 * @return  the value of resource.id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.id
	 * @param id  the value for resource.id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.name
	 * @return  the value of resource.name
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.name
	 * @param name  the value for resource.name
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.user_id
	 * @return  the value of resource.user_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.user_id
	 * @param userId  the value for resource.user_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.calendar_id
	 * @return  the value of resource.calendar_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getCalendarId() {
		return calendarId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.calendar_id
	 * @param calendarId  the value for resource.calendar_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setCalendarId(Integer calendarId) {
		this.calendarId = calendarId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.location_id
	 * @return  the value of resource.location_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getLocationId() {
		return locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.location_id
	 * @param locationId  the value for resource.location_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setLocationId(Integer locationId) {
		this.locationId = locationId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.notes
	 * @return  the value of resource.notes
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.notes
	 * @param notes  the value for resource.notes
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.status
	 * @return  the value of resource.status
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.status
	 * @param status  the value for resource.status
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column resource.type
	 * @return  the value of resource.type
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column resource.type
	 * @param type  the value for resource.type
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setType(Integer type) {
		this.type = type;
	}
}