package io.starter.model;

import java.util.ArrayList;
import java.util.List;

public class Location {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.owner_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer ownerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.type
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.name
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.description
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.address_1
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String address1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.address_2
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String address2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.city
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.state
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String state;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.postal_code
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String postalCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.phone
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.status
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.email
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.notes
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String notes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.longitude
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Float longitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.latitude
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Float latitude;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.locationcode
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private Integer locationcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.url
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column location.image_url
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	private String imageUrl;


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.id
	 * @return  the value of location.id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.id
	 * @param id  the value for location.id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.owner_id
	 * @return  the value of location.owner_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getOwnerId() {
		return ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.owner_id
	 * @param ownerId  the value for location.owner_id
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setOwnerId(Integer ownerId) {
		this.ownerId = ownerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.type
	 * @return  the value of location.type
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.type
	 * @param type  the value for location.type
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.name
	 * @return  the value of location.name
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.name
	 * @param name  the value for location.name
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.description
	 * @return  the value of location.description
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.description
	 * @param description  the value for location.description
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.address_1
	 * @return  the value of location.address_1
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getAddress1() {
		return address1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.address_1
	 * @param address1  the value for location.address_1
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.address_2
	 * @return  the value of location.address_2
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getAddress2() {
		return address2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.address_2
	 * @param address2  the value for location.address_2
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.city
	 * @return  the value of location.city
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.city
	 * @param city  the value for location.city
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.state
	 * @return  the value of location.state
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getState() {
		return state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.state
	 * @param state  the value for location.state
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.postal_code
	 * @return  the value of location.postal_code
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getPostalCode() {
		return postalCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.postal_code
	 * @param postalCode  the value for location.postal_code
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setPostalCode(String postalCode) {
		this.postalCode = postalCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.phone
	 * @return  the value of location.phone
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.phone
	 * @param phone  the value for location.phone
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.status
	 * @return  the value of location.status
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.status
	 * @param status  the value for location.status
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.email
	 * @return  the value of location.email
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.email
	 * @param email  the value for location.email
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.notes
	 * @return  the value of location.notes
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.notes
	 * @param notes  the value for location.notes
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.longitude
	 * @return  the value of location.longitude
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Float getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.longitude
	 * @param longitude  the value for location.longitude
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setLongitude(Float longitude) {
		this.longitude = longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.latitude
	 * @return  the value of location.latitude
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Float getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.latitude
	 * @param latitude  the value for location.latitude
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setLatitude(Float latitude) {
		this.latitude = latitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.locationcode
	 * @return  the value of location.locationcode
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public Integer getLocationcode() {
		return locationcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.locationcode
	 * @param locationcode  the value for location.locationcode
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setLocationcode(Integer locationcode) {
		this.locationcode = locationcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.url
	 * @return  the value of location.url
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.url
	 * @param url  the value for location.url
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column location.image_url
	 * @return  the value of location.image_url
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public String getImageUrl() {
		return imageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column location.image_url
	 * @param imageUrl  the value for location.image_url
	 * @mbggenerated  Tue Apr 07 16:38:07 PDT 2015
	 */
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	private List calendars = new ArrayList();
	
	
	public List getCalendars() {
		return calendars;
	}

	public void setCalendars(List calendars) {
		this.calendars = calendars;
	}

	private List technicians = new ArrayList();

	public List getTechnicians() {
		return technicians;
	}

	public void setTechnicians(List technicians) {
		this.technicians = technicians;
	}
	
}